// เปลี่ยนข้อมูลตรงนี้ แล้วบันทึกเป็น UTF-8
window.LOVE_CONFIG = {
  recipient: "คนเก่งของเรา",
  sender: "คนที่อยากดูแลเธอ",
  // วางลิงก์รูปโดยตรงจาก Discord (Copy Link ของรูป ไม่ใช่ลิงก์ข้อความ)
  // หรือใช้รูปในเครื่อง เช่น "assets/our-photo.jpg"
  photoUrl: "",
  photoCaption: "รอยยิ้มของเธอ เป็นเรื่องโปรดของเรา ♡",
  pageTitle: "สวนเล็ก ๆ ของเรา · A little place for you",
  noPhotoTitle: "สวนเล็ก ๆ นี้ ตั้งใจทำให้เธอ",
  notReadyMessage: "ได้เลยนะ ไม่ต้องรีบตอบ ดูแลหัวใจตัวเองก่อน เราเคารพการตัดสินใจของเธอเสมอ ♡",
  // แก้เฉพาะข้อความด้านขวา ภายในเครื่องหมายคำพูด
  // ใช้ \n เพื่อขึ้นบรรทัดใหม่ ไม่ต้องใส่ HTML
  texts: {
    ".intro .eyebrow": "A LITTLE SOMETHING, JUST FOR YOU",
    ".intro p": "มีสวนเล็ก ๆ อยากพาเธอไปดู",
    "#enter": "เปิดประตูหัวใจ ↗",
    ".intro small": "ค่อย ๆ เปิด ค่อย ๆ รู้สึก ไม่ต้องรีบเลย",
    ".nav-note": "มีจดหมายถึงเธอ ↗",
    ".pill": "●  A SAFE LITTLE PLACE FOR YOUR HEART",
    "h1": "โลกอาจใจร้าย\nแต่ตรงนี้…\nมีรักให้เธอนะ",
    ".hero-description": "ไม่ต้องเก่งทุกวัน ไม่ต้องยิ้มตลอดเวลาก็ได้\nในสวนเล็ก ๆ แห่งนี้ เธอเป็นตัวเองได้เสมอ",
    "#reveal": "มีบางอย่างอยากให้เธอเห็น ♡",
    ".tiny-note": "ทำขึ้นด้วยความตั้งใจ ให้เธอคนเดียว",
    ".floating-note small": "เธอคู่ควรกับความรักที่อ่อนโยน",
    ".letter .section-label": "01 — A LETTER FROM MY HEART",
    ".letter-title .handwritten": "A little love note",
    ".letter-title h2": "ถึงเธอ\nที่เราดีใจมาก\nที่ได้เจอ ♡",
    ".paper-date": "จดหมายฉบับนี้ เป็นของเธอ",
    ".letter-paper h3": "ไม่ต้องรีบกลับมาสดใสก็ได้นะ",
    ".letter-paper p:nth-of-type(1)": "เรื่องที่ผ่านมาอาจทำให้หัวใจเธอเหนื่อย และเราอาจไม่ได้เข้าใจทุกความรู้สึก แต่เราอยากฟัง เมื่อไหร่ที่เธอพร้อมจะเล่า",
    ".letter-paper p:nth-of-type(2)": "สิ่งที่เธอเคยเจอ ไม่ได้ทำให้คุณค่าของเธอน้อยลงเลย เธอยังสมควรได้รับความรักที่ให้เกียรติ ความสบายใจ และพื้นที่ที่จะเป็นตัวเอง",
    ".letter-paper p:nth-of-type(3)": "เราไม่ได้อยากให้เธอลืมทุกอย่างในวันเดียว แค่อยากค่อย ๆ รู้จักเธอให้มากขึ้น อยู่ข้าง ๆ ในวันที่ดี และรับฟังในวันที่ไม่ง่าย",
    ".letter-paper .highlight": "กับเรา… เธอไม่ต้องพยายามน่ารักกว่านี้\nแค่เป็นเธอ ก็มีความหมายมากแล้ว",
    ".promises .section-label": "02 — THE LITTLE THINGS I MEAN",
    ".promises h2": "รักที่เราอยากให้เธอรู้สึก",
    ".section-sub": "ไม่ใช่คำสัญญาว่าทุกวันจะสมบูรณ์แบบ แต่คือความตั้งใจในทุกวัน",
    ".promise-grid article:nth-child(1) h3": "มีคนรับฟังจริง ๆ",
    ".promise-grid article:nth-child(1) p": "เธอพูดได้ทั้งเรื่องเล็กและเรื่องใหญ่\nความรู้สึกของเธอสำคัญกับเรา",
    ".promise-grid article:nth-child(2) h3": "เป็นตัวเองได้เต็มที่",
    ".promise-grid article:nth-child(2) p": "เคารพพื้นที่และการตัดสินใจของเธอ\nไม่ต้องเปลี่ยนตัวเองเพื่อให้ถูกรัก",
    ".promise-grid article:nth-child(3) h3": "ค่อย ๆ ไปด้วยกัน",
    ".promise-grid article:nth-child(3) p": "ถ้าเธอยังต้องการเวลา เราเข้าใจ\nความรักไม่จำเป็นต้องรีบเลย",
    ".memory .section-label": "03 — MY FAVORITE LITTLE MOMENT",
    ".memory .handwritten": "My favorite view is you.",
    ".memory h2": "แค่มีเธอ\nวันธรรมดาก็พิเศษ",
    ".memory-copy p:not(.handwritten)": "อยากมีวันธรรมดาอีกหลาย ๆ วันด้วยกัน\nกินของอร่อย เล่าเรื่องเล็ก ๆ แล้วหัวเราะไปด้วยกัน",
    "#show-photo": "เปิดของขวัญอีกครั้ง ↗",
    ".proposal .section-label": "04 — ONE LITTLE QUESTION",
    ".proposal .handwritten": "Can our little story begin?",
    ".proposal h2": "ให้เราเป็นแฟนเธอ\nได้ไหม?",
    ".proposal > p:not(.handwritten):not(.answer-feedback)": "ถ้าเธอพร้อม เราอยากเริ่มเรื่องราวบทใหม่ไปด้วยกัน\nและถ้ายังไม่พร้อม คำตอบของเธอก็มีความหมายเสมอ",
    "#yes": "เป็นแฟนกันนะ ♡",
    "#later": "ขอเวลาอีกนิดนะ",
    ".proposal small": "ไม่มีคำตอบไหนทำให้คุณค่าของเธอลดลงเลย",
    "footer p": "ตั้งใจทำทุกความรู้สึก · ให้เธอคนเดียว ♡",
    "#gift-dialog .handwritten": "A little gift for you",
    "#gift-title": "คนนี้ไง… คนที่ทำให้เรายิ้ม",
    "#gift-dialog > p:not(.handwritten)": "ขอบคุณที่เข้ามาเป็นความน่ารักในวันธรรมดาของเรา ♡",
    "#read-letter": "ไปอ่านจดหมายด้วยกัน ↓",
    "#yes-dialog .handwritten": "The beginning of us.",
    "#yes-title": "ดีใจที่ได้เป็น\nคนข้าง ๆ เธอนะ",
    "#yes-dialog > p:not(.handwritten)": "จากนี้ ค่อย ๆ เรียนรู้และดูแลกันไปนะ\nขอบคุณที่ให้เราเป็นส่วนหนึ่งในวันของเธอ ♡",
    "#back-garden": "เก็บรอยยิ้มนี้ไว้ ♡"
  }
};
